/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./assets/templates/**/*.html",
    "./templates/**/*.html",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Outfit', 'sans-serif'],
      },
      colors: {
        'primary':                'var(--md-color-primary)',
        'on-primary':             'var(--md-color-on-primary)',
        'primary-container':      'var(--md-color-primary-container)',
        'on-primary-container':   'var(--md-color-on-primary-container)',
        'secondary':              'var(--md-color-secondary)',
        'on-secondary':           'var(--md-color-on-secondary)',
        'secondary-container':    'var(--md-color-secondary-container)',
        'on-secondary-container': 'var(--md-color-on-secondary-container)',
        'tertiary':               'var(--md-color-tertiary)',
        'on-tertiary':            'var(--md-color-on-tertiary)',
        'tertiary-container':     'var(--md-color-tertiary-container)',
        'on-tertiary-container':  'var(--md-color-on-tertiary-container)',
        'error':                  'var(--md-color-error)',
        'on-error':               'var(--md-color-on-error)',
        'error-container':        'var(--md-color-error-container)',
        'on-error-container':     'var(--md-color-on-error-container)',
        'surface':                'var(--md-color-surface)',
        'on-surface':             'var(--md-color-on-surface)',
        'on-surface-variant':     'var(--md-color-on-surface-variant)',
        'surface-container-lowest':  'var(--md-color-surface-container-lowest)',
        'surface-container-low':     'var(--md-color-surface-container-low)',
        'surface-container':         'var(--md-color-surface-container)',
        'surface-container-high':    'var(--md-color-surface-container-high)',
        'surface-container-highest': 'var(--md-color-surface-container-highest)',
        'outline':                'var(--md-color-outline)',
        'outline-variant':        'var(--md-color-outline-variant)',
        'inverse-surface':        'var(--md-color-inverse-surface)',
        'inverse-on-surface':     'var(--md-color-inverse-on-surface)',
        'inverse-primary':        'var(--md-color-inverse-primary)',
        'surface-tint':           'var(--md-color-surface-tint)',
        'scrim':                  'var(--md-color-scrim)',
        'success':                'var(--md-color-success)',
        'on-success':             'var(--md-color-on-success)',
        'success-container':      'var(--md-color-success-container)',
        'warning':                'var(--md-color-warning)',
        'on-warning':             'var(--md-color-on-warning)',
        'warning-container':      'var(--md-color-warning-container)',
        'info':                   'var(--md-color-info)',
        'on-info':                'var(--md-color-on-info)',
        'info-container':         'var(--md-color-info-container)',
      },
      borderRadius: {
        'xs':   '4px',
        'sm':   '8px',
        'md':   '12px',
        'lg':   '16px',
        'xl':   '28px',
      },
    },
  },
  plugins: [],
}
