/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./assets/templates/**/*.html",
    "./templates/**/*.html",
    // search.js construit la palette Ctrl+K en JS : sans ce glob, aucune de ses
    // classes n'était générée et la modale s'affichait sans fond ni bordure.
    "./assets/static/*.js",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Outfit', 'sans-serif'],
      },
      // Les tokens sont exposés en canaux RGB avec placeholder alpha : sans lui,
      // Tailwind ne sait pas composer l'opacité et omet SILENCIEUSEMENT tous les
      // utilitaires du type bg-primary/10, border-primary/30 ou bg-scrim/50.
      colors: {
        'primary':                   'rgb(var(--md-color-primary-rgb) / <alpha-value>)',
        'on-primary':                'rgb(var(--md-color-on-primary-rgb) / <alpha-value>)',
        'primary-container':         'rgb(var(--md-color-primary-container-rgb) / <alpha-value>)',
        'on-primary-container':      'rgb(var(--md-color-on-primary-container-rgb) / <alpha-value>)',
        'secondary':                 'rgb(var(--md-color-secondary-rgb) / <alpha-value>)',
        'on-secondary':              'rgb(var(--md-color-on-secondary-rgb) / <alpha-value>)',
        'secondary-container':       'rgb(var(--md-color-secondary-container-rgb) / <alpha-value>)',
        'on-secondary-container':    'rgb(var(--md-color-on-secondary-container-rgb) / <alpha-value>)',
        'tertiary':                  'rgb(var(--md-color-tertiary-rgb) / <alpha-value>)',
        'on-tertiary':               'rgb(var(--md-color-on-tertiary-rgb) / <alpha-value>)',
        'tertiary-container':        'rgb(var(--md-color-tertiary-container-rgb) / <alpha-value>)',
        'on-tertiary-container':     'rgb(var(--md-color-on-tertiary-container-rgb) / <alpha-value>)',
        'error':                     'rgb(var(--md-color-error-rgb) / <alpha-value>)',
        'on-error':                  'rgb(var(--md-color-on-error-rgb) / <alpha-value>)',
        'error-container':           'rgb(var(--md-color-error-container-rgb) / <alpha-value>)',
        'on-error-container':        'rgb(var(--md-color-on-error-container-rgb) / <alpha-value>)',
        'surface':                   'rgb(var(--md-color-surface-rgb) / <alpha-value>)',
        'on-surface':                'rgb(var(--md-color-on-surface-rgb) / <alpha-value>)',
        'on-surface-variant':        'rgb(var(--md-color-on-surface-variant-rgb) / <alpha-value>)',
        'surface-container-lowest':  'rgb(var(--md-color-surface-container-lowest-rgb) / <alpha-value>)',
        'surface-container-low':     'rgb(var(--md-color-surface-container-low-rgb) / <alpha-value>)',
        'surface-container':         'rgb(var(--md-color-surface-container-rgb) / <alpha-value>)',
        'surface-container-high':    'rgb(var(--md-color-surface-container-high-rgb) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--md-color-surface-container-highest-rgb) / <alpha-value>)',
        'outline':                   'rgb(var(--md-color-outline-rgb) / <alpha-value>)',
        'outline-variant':           'rgb(var(--md-color-outline-variant-rgb) / <alpha-value>)',
        'inverse-surface':           'rgb(var(--md-color-inverse-surface-rgb) / <alpha-value>)',
        'inverse-on-surface':        'rgb(var(--md-color-inverse-on-surface-rgb) / <alpha-value>)',
        'inverse-primary':           'rgb(var(--md-color-inverse-primary-rgb) / <alpha-value>)',
        'surface-tint':              'rgb(var(--md-color-surface-tint-rgb) / <alpha-value>)',
        'scrim':                     'rgb(var(--md-color-scrim-rgb) / <alpha-value>)',
        'success':                   'rgb(var(--md-color-success-rgb) / <alpha-value>)',
        'on-success':                'rgb(var(--md-color-on-success-rgb) / <alpha-value>)',
        'success-container':         'rgb(var(--md-color-success-container-rgb) / <alpha-value>)',
        'warning':                   'rgb(var(--md-color-warning-rgb) / <alpha-value>)',
        'on-warning':                'rgb(var(--md-color-on-warning-rgb) / <alpha-value>)',
        'warning-container':         'rgb(var(--md-color-warning-container-rgb) / <alpha-value>)',
        'info':                      'rgb(var(--md-color-info-rgb) / <alpha-value>)',
        'on-info':                   'rgb(var(--md-color-on-info-rgb) / <alpha-value>)',
        'info-container':            'rgb(var(--md-color-info-container-rgb) / <alpha-value>)',
      },
      borderRadius: {
        'xs':   '4px',
        'sm':   '8px',
        'md':   '12px',
        'lg':   '16px',
        'xl':   '28px',
      },
    },
  },
  plugins: [],
}
