---
- name: Install Basic Tools
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Curl, Git, Htop, Vim
      apt:
        pkg:
          - curl
          - git
          - htop
          - vim
          - wget
        state: present
